name: Code analysis and security scan.

on:
  pull_request: 
    branches: ["main"]

  workflow_dispatch:

jobs:
    code-scans:
      runs-on: ubuntu-latest
  
      steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessary to fetch all tags and history
  
  ################################################################
  ###               SONAR CLOUD SCAN                           ###
  ### Drops the build if any bugs or vulnerabilities are found.###
  ###            Using the default quality gate.               ###
  ###        Connected to my personal Sonar Cloud account      ###
  ################################################################
  
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

  ###########################################################
  ###       Code scan | If fails, drops the action.       ###
  ###       Connected to my personal Snyk account         ###
  ###     The code owner receives an email notification   ###
  ### Possible to configure Slack notification if needed  ###
  ###########################################################               
                 
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:        
           args: --severity-threshold=high --policy-path=.snyk
        continue-on-error: true